# docker run -d --rm --name mongo -p 27017:27017 mongodbdata:/data/db mongo

version: "26.0.2"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: