# docker run -d --rm --name mongo -p 27017:27017 mongodbdata:/data/db mongo

version: "26.0.2"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672 #used by the services to publish messages to, or to consume messages from rabbitMQ
      - 15672:15672 #used to be able to go to the rabbitMQ portal
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq #to store the value in the same place and not random name each time
    

volumes:
  mongodbdata:
  rabbitmqdata: